#sync-csvs.yml
name: Sync CSVs
on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Download CSVs
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1WYtDTG0mg_jcCBrjHs53rflPrVQLN-xlU0UBdIYFnFg/export?format=csv" -o static/data/towns.csv
          curl -L "https://docs.google.com/spreadsheets/d/1ixfJDFK1FRsSfAkbebQxMbhpFaeb-C3jit0IoVRnKyo/export?format=csv" -o static/data/businesses.csv

      - name: Download Events CSV
        run: |
            mkdir -p static/data/events
            files=$(gcloud storage ls gs://18lzxsWJFhZz0RBmPrkPVBMiOdG-g4SFj/*.csv)
            for file in $files; do
            filename=$(basename $file)
            gcloud storage cp $file static/data/events/$filename
            done

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git remote set-url origin https://${{ secrets.EVENTS_EXPORT }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Auto-sync CSVs" || exit 0
          git push