#sync-json.yml
name: Sync JSON files
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Download towns JSON
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=1LKTfbNJFvTpYJwNKZAZi5Et0xhio7izt" -o static/data/towns.json

      - name: Download businesses JSON
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=1n9lq1_OFQxLN_lGmsKisfcGgD9_iiPJ2" -o static/data/businesses.json

      - name: Download events JSON
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=1Sv-9H8K10OLbo4-inWcSrUeaSmu2fzgh" -o static/data/events.json


      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git remote set-url origin https://${{ secrets.EVENTS_EXPORT }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Auto-sync JSON files" || exit 0
          git push
